trigger:
  branches:
    include:
    - main
    - feature/*

pool:
  vmImage: 'ubuntu-latest'


stages:
- stage: deploy
  displayName: deploy
  jobs:
  - job: deploy
    steps:
    - task: AzureRmWebAppDeployment@4
      inputs:
        ConnectionType: 'AzureRM'
        azureSubscription: 'Azure subscription 1(c9b4f1f5-2965-443a-bdba-e07989ae57dc)'
        appType: 'webAppLinux'
        WebAppName: 'calify-web-alpha'